<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LVN01000147" ignored="0" tests="5" failures="2" timestamp="2022-01-25T16:06:46 ICT" time="3.867" errors="0">
  <testcase name="checkVaccined" time="0.771" classname="PesonTest"/>
  <testcase name="checkVaccined" time="0.011" classname="PesonTest">
    <failure type="java.lang.AssertionError" message="expected [18] but found [21]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [21]
at PesonTest.checkVaccined(PesonTest.java:51)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkVaccined -->
  <testcase name="checkVaccined" time="0.0" classname="PesonTest">
    <failure type="java.lang.AssertionError" message="expected [18] but found [51]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [51]
at PesonTest.checkVaccined(PesonTest.java:51)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkVaccined -->
  <testcase name="testPersonVaccin" time="0.0" classname="PesonTest"/>
  <testcase name="testPesonVaccin2" time="0.0" classname="PesonTest"/>
</testsuite>
